version: '3'
services:
  app:
    image: "melonboy10/hermes-minecraft-server-manager:latest"
    container_name: "hermes-mcsm"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./servers:/app/servers
    # Database volume
    # Uncomment if you want to keep your data when updating the container
      - ./database:/app/database/pb_data
    ports:
    # Website external port (feel free to change) : internal port (don't change)
      - "3000:3000"
    # Database external port (feel free to change) : internal port (don't change)
      - "8090:8090"
    environment:
    # Default user account for managing the database
      - PUBLIC_ROOT_DOMAIN=example.com
      - PUBLIC_PORT_MIN=25565
      - PUBLIC_PORT_MAX=25565
      - PUBLIC_DEFAULT_ICON_URL=https://example.com/example.png
      - PUBLIC_TIME_UNTIL_DELETION_AFTER_SHUTDOWN=168 # In hours

      - CLOUDFLARE_TOKEN=<token>
      - CLOUDFLARE_ZONE_ID=<zone_id>

    # This is the default user account for managing the database used by the server internally
    # Feel free to change the email and password, it will create the account if it doesn't exist
      - POCKETBASE_INTERNAL_ADMIN_EMAIL=internal@example.com
      - POCKETBASE_INTERNAL_ADMIN_PASSWORD=password



    restart: unless-stopped